@domain = http://localhost:4000
@AccessToken = {{loginToken.response.body.$.access_token}}
# @AccessToken = "구글 소셜 로그인 테스트 시 이쪽에 토큰 값 입력한 뒤 2번째 줄 주석처리"

###
# 사용자 로그인
# @name loginToken
POST {{domain}}/auth/login
Content-Type: application/json

{
  "email": "jgw987@gmail.com",
  "password": "123qweQWE!"
}

###
# 그룹 메시지 생성
POST {{domain}}/mails/group-message
Content-Type: application/json
Authorization: Beaer {{AccessToken}}

{
  "groupId": 2,
  "message": "안녕하세요 여러분 챌린지반 수업이 곧 시작됩니다."
}

### 
# 메일 전체 조회
GET {{domain}}/mails
Authorization: Bearer {{AccessToken}}

###
# 메일 상세 조회
GET {{domain}}/mails/2
Authorization: Bearer {{AccessToken}}