@domain = http://localhost:4000
@AccessToken = {{loginToken.response.body.$.access_token}}
# @AccessToken = "구글 소셜 로그인 테스트 시 이쪽에 토큰 값 입력한 뒤 2번째 줄 주석처리"


###
# 사용자 회원가입
POST {{domain}}/users
Content-Type: application/json

{
  "email": "user2@gmail.com",
  "password": "123qweQWE!",
  "nick_name": "일반좁밥"
}

###
# 사용자 로그인
# @name loginToken
POST {{domain}}/auth/login
Content-Type: application/json

{
  "email": "admin10000@gmail.com",
  "password": "123qweQWE!"
}

###
# 엑세스 토큰 재발급 (로그인 시간 연장)
# @name loginToken
POST {{domain}}/auth/refresh
Authorization: Bearer {{AccessToken}}

###
# 스페이스 클래스 전체 조회 (타입, 최대수용인원, 가격)
GET {{domain}}/spaces/classes
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

###
# 스페이스 멤버의 역할 변경
PATCH {{domain}}/space-members/change-role
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

{
  "spaceId": 1,
  "targetUserId": 2,
  "newRole": 2
}

###
# 학습공간에서 전체 멤버 정보 조회
GET {{domain}}/space-members/1
Authorization: Bearer {{AccessToken}}
Content-Type: application/json